sudo: required
language: node_js
node_js:
- '6'
- '6.1'
addons:
  apt: 
  sources: — mongodb-3.0-precise
  packages: — mongodb-org-server
services:
- docker
- mongodb
notifications:
  email:
  - julioeffgen@gmail.com
  - picorelli.luiz@gmail.com
  - vinicius.ronconi@gmail.com
env:
  global:
    DOCKER_EMAIL: vinicius.ronconi@gmail.com
    DOCKER_USER: viniciusronconi
    COMMIT:
    - ${TRAVIS_COMMIT::6}
    DOCKER_PASS:
      secure: AUuwlkaJBOPCwHBR5yYW2vFAvGcJlgM0PfYXg0x0b88MKYEytMQ0dVOcRiAJfxsC5vZPH4jS429JxJqoeJROmi/sDKGxaUckh1Pn8yIAtvwHqleRXUMP6efatn/NWmf8mk1NXyTc1WAUR423tpgkYmwie610yAszHbqhi1tbMuxtYPZRp1X4B1f1sK4fBLEuFf0whV2OIDbqcRk4SkF7cx753lcDtJEc2reRGTJerYr9je1qLvflB3/ENoiepBBEjC0prLiJkLmt4tDPpSi6dt2rcEZBPI6kZVMfWLVmI4PuCaVifMoJUM8z63156KpxbGfNd6ObzDrX9m6YUp8nGrM2ZLas8OpDbGPJV1kdr5QWHPX0gVq7HqOXQgUUlKsSTzhYuMvFiLRyEpyohQwCdpl49r34iLKb5Ta3OTpSPBLpjRZJjK2KrqTqDqKfzCCOnEma5sBfKio0ZHqcMI4Bh4pYJhk9CC61BGmSBPkzOarqNx3Ho1IBTSC4QEeERKNnrJBX8rq13Ll1HL7dRNZEGo7Db8FseNsvYlkQNtJ4upJLUUDX5zPf5Ucdcw8/4sXLIJDi0fWBhqh9LfQM7HLRxddPY/WhFfEVBB5Q9YCi09RfVJ0DGcnTK9V1zvgKUrpFsjX/XNfCvfDpS366PJU9FfyYXhT4uIupT9o4ll7fCVI=
before install:
- curl https://install.meteor.com/ | sh
install:
- npm install
after_success:
- echo $DOCKER_USER
- docker login -u=$DOCKER_USER -p=$DOCKER_PASS
- export REPO=$DOCKER_USER/practicalshooting
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- echo $REPO
- echo $TAG
- echo $COMMIT
- echo $REPO:$TAG:$COMMIT
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
deploy:
  skip_cleanup: true
  on:
    branch: master
