sudo: required
language: node_js
node_js:
- '6'
- '6.1'
addons:
  apt: 
  sources: — mongodb-3.0-precise
  packages: — mongodb-org-server
services:
- docker
- mongodb
notifications:
  email:
  - julioeffgen@gmail.com
  - picorelli.luiz@gmail.com
  - vinicius.ronconi@gmail.com
env:
  global:
    DOCKER_EMAIL: vinicius.ronconi@gmail.com
    DOCKER_USER: viniciusronconi
    DOCKER_PASS:
      secure: cmvUcxI8EZyrCmMIsTCFFfEURKvBgPxblyvIjY89uMuWMQ94qoZWYkS+CJBsspfKEL8hEeoDdW23+FP7N28ue+c0ZqSdCTBJ5rv4UE0DRWuVTId+Y66FqSUaHtJY3ZOWOXI9iyWl7c0AJUMxzeeblplaG4kPoK6bMM/iUvHsKH5Rj0GZUl0NLakFBs8vMv8Xr5SECR6lKR8b3vvdCVOdaNOSDt7JgJpJZ0LuLMM1xjc2qFef/SCzJ7qBZ43kB8szUkB72RQ3sxlwlL/F3tuOGrP/YekTOeD1BUxuIYSrdln7ssIhY3TRBdR0coxEwJEUOWSIFVaLQGJsz+tY41/Wun9/lHhj/mEgGi2jBmGh0ZKsrINAxbGvpHNX5ynXlqVpgheiasIJgUyBNIMMYIVeviuKhCTM0bTjN6SJbiw8x3//9OcYEPdQThtLgqDPsOG9B2E5GHYDGNPPs8xwxUt9dpyOBBPhav/7aQq4ohc74F1ZQhhZu0Nsk5AFnHc0k5nBXJDmge2nLdfQlHBYf8glQg4xwmYl/IUj62cW9DLRI6rwlnP8Gf8Hr/iGNCBeuK7db3BMgJle+nillFqBoJKV5migX3tLq8Y1OrwV0HRyi8S/V9xZF5K1hIEHuKPgncve5yCnTgwKG3FHMog5R+UtGj1PRpSJ0dZYBuuYxCpVay4=
    COMMIT:
    - ${TRAVIS_COMMIT::6}
before install:
- curl https://install.meteor.com/ | sh
install:
- npm install
after_success:
- echo $DOCKER_USER
- docker login -u=$DOCKER_USER -p=$DOCKER_PASS
- export REPO=$DOCKER_USER/practicalshooting
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- echo $REPO
- echo $TAG
- echo $COMMIT
- echo $REPO:$TAG:$COMMIT
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
deploy:
  skip_cleanup: true
  on:
    branch: master
