sudo: required
language: node_js
node_js:
  - "6"
  - "6.1"
services:  # Need to confirm which services must be added here
  - docker
  - mongodb
before install:
  - curl https://install.meteor.com/ | sh
install:
  - npm install
deploy:
  skip_cleanup: true
  on:
    branch: master
after_deploy:
  echo "Deployed...."
notifications:
  email:
    - julioeffgen@gmail.com
    - picorelli.luiz@gmail.com
    - vinicius.ronconi@gmail.com
