sudo: required
language: node_js
node_js:
  - "6"
  - "6.1"
services:  # Need to confirm which services must be added here
  - docker
  - mongodb
before install:
  - curl https://install.meteor.com/ | sh
install:
  - npm install
