sudo: required
language: node_js
node_js:
- '6'
- '6.1'
addons:
  apt: 
  sources: — mongodb-3.0-precise
  packages: — mongodb-org-server
services:
- docker
- mongodb
notifications:
  email:
  - julioeffgen@gmail.com
  - picorelli.luiz@gmail.com
  - vinicius.ronconi@gmail.com
env:
  global:
    secure: "J4OwCOUzZzCV36mLhq2hAj8g3u1NBXix8reQ7l+7gP4tBhmrxp2w953ao2hMbXtHiWfv5fWwFQaQ/rbbdtGfH/rm/vzEaOuzN4HFPK8Mq0ahIHkhGxbM7QaooCHj3E5cKXAEOPdtfISU9iKK68lDA2aEgIi8f7+4Lg7vwmN8Y0YXbQAyS73yef0/CCEbMWlztpIgfI0EY72DTULMQPsaOnoQY6++P47/FbaUXMI76CBvDzSAMAK6g+z4LY8B6Y3T3bQf9/vEBrdxy0BHnAOBGfNh2w9dYzcQKKP0jA1n858mg8Gkq5FVOStD2Rd+WFdKlP/o51ImwWIkb+sBgy0NhggVEWVrHtqWA53yM8gT4ExPGNwACDQebULIeG7Xd+YZK/D6+uK1wkq2GTKKcbi8kL/6O77mILiw0KFUeoXuOaNu/x/XoAEoAaqti2TvUue/LbPcdzzYQ3OYIAXjeM+7aYozkx9PfvzVzYVv06Xhg0nDW+FDy0xvQhRbQgtv4i/OQhenRCA8ObuEWgG+LnPaeHkZngCYe0B20CGAp+92X7sQLPIUHBh0tQEwhDT2Te04LvOjiJX5psgijEw3edKs02vka1DMmOjr+1WB4VFtrKDAaPS/IIKdCVYAciZ4pISVf3TYuOpzQ4i1FcdjyWF25fGNh0WlHuyHGQXBM21i33Y="
    secure: "KDiwjz7bji+hKNzwGk6CTKJMDrmiOJ+CyrNrNHbk/dD/it5lPMSy25pmz1JlrIa+/kqfXrKuTyDPdVTnoXmfYuo1KkfbDerNyTYELuMtX3xb1nmTJmc/8EeKCZqk+5sA15pEJfKN74VcaGhgyjFk4jaeqh78V04LZz3fBjZZerpm5MC78mXJqswWQCvHf5cCLzrPRJBdlXmFclmQ5ogRDZYESxPD02kBLLfYWrT+RsXU2ZpN4IaGEbwM/CpE6xHqmpTImtjmBuc0YlyweOodj/8tm9HM3qy2lcBwTXTGRSOIbU+jvHX5ssTaBmTzPwpcpU0hnA30ueO8bAiegXodUL2PGNbh4/AVvzBngbiTzwg7et/DqUcZMN0DaLhwaz69TFQSnavHf5Mxvto+ZDnDkhkWWBnkAqOb3oBiU6Bg8+FkJjemE9eVTFGTimCkz1dH+O9Sib/2jyV9rirLO1o4B28MlUshcZSDCP/iBQVeCnJkfuKnC/MZj0wWjDjQ1fbW1zlPnMdGNjglfpPD4nwJjzpIIBAwrJGDVpzQJ8p9ovY1+7RKH81VnN1BBBrDwNSDSxHFgwcODQ5TgDSaPJ9hi/huxRuoebbe7WJnLCBRCcERCumu9/bmsl9YYGsjnyCMC5h7w3GY06erhWhMc8f/o5lcpehoMVlc8tWcSMsc0lE="
    secure: "OAI8krr4klm8ph4AnqOH9YsizHqndiF5yBXIYOsQQ32Vl0Uhch9ntVytslgXFMHiAyAfUGpxLaYvBaSjtq+ODQb3bys1BPrYQwzQ5tkOaz5gALECG0JBcG3IFYm9IRHvSD+Gv8pPPkI3aOZmoYaaUuJ7IMQ6obF6oiCVjYLK09tKKI8Cy6Tcv1f0Z/i62HC1RdpmaTRParhCVSlPMhiofxkrCVb1XxhBWu2y7RTMbE6RDYQ77MhJyui1O+TU2pREw/YjD1W6Uf/a4ha2Qrrh6sdY4PnutSPG+XPKsYUURQg+T/T1YvK6zDNrgqYLVae9j1uKyYh5uDs9Kj4ZoCOKYSauc12W3jVm92v8vybgAmC/5cyyqdNYRpjvlO826Wmng6Vm5Znj4cotg4Ra2TlVagZyx9MAb3A5mpD8fX16k8MIsfFr8cRuo5tVzq49YffwlJZk2f9kyWTD4KY6NKXjakwsmH5VKjZdn2/7CJUVa1fGpZQTr7TjV/2mmc/z3Pn6GyZ9HQQRFrd5yiDErPavZ9lbjpQR3HV3Rk2PAv12DgWqsXjSoURfXIBi4KrWJo+BA706Vx9VLN260bNb5tt423GCrnDEbsm5qLrDjptCrbwAwo0yqXoxX6r1DJ/mloiO+P8m8ehC3LhLutKuBCfeoFWYHKalyi5kbvU1sHgui/w="
    COMMIT:
    - ${TRAVIS_COMMIT::6}
before install:
- curl https://install.meteor.com/ | sh
install:
- npm install
after_success:
- echo $DOCKER_USER
- docker login -u=$DOCKER_USER -p=$DOCKER_PASS
- export REPO=$DOCKER_USER/practicalshooting
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- echo $REPO
- echo $TAG
- echo $COMMIT
- echo $REPO:$TAG:$COMMIT
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
deploy:
  skip_cleanup: true
  on:
    branch: master
