data:
  extends:
    file: docker-compose-common.yml
    service: data

db:
  extends:
    file: docker-compose-common.yml
    service: db
  expose:
    - "27017"
  volumes_from:
    - data

app:
  extends:
    file: docker-compose-common.yml
    service: app
  ports:
    - "80:80"
  links:
    - db:db
  environment:
   - REPO=https://github.com/julioeffgen/practicalshooting/
   - ROOT_URL=http://52.67.97.169:80
   - MONGO_URL=mongodb://db/practicalshooting
