data:
  extends:
    file: docker-compose-common.yml
    service: data

db:
  extends:
    file: docker-compose-common.yml
    service: db
  expose:
    - "27017:27017"
  volumes_from:
    - data

app:
  extends:
    file: docker-compose-common.yml
    service: app
  ports:
    - "3000:3000"
  links:
    - db:db
  volumes:
    - .:/src
